/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    Auth: {
        identityPoolId: 'eu-central-1:37e71ac5-c76f-4c5f-944a-e536d2e6d730', //REQUIRED - Amazon Cognito Identity Pool ID
        region: 'eu-central-1', // REQUIRED - Amazon Cognito Region
        userPoolId: 'eu-central-1_0gtcpHQiS', //OPTIONAL - Amazon Cognito User Pool ID
        userPoolWebClientId: '3ha42c9i4tfdoo3fipmt67ndn4', //OPTIONAL - Amazon Cognito Web Client ID
        awsProjectRegion: "eu-central-1"
    },
    Storage: {
        AWSS3: {
            bucket: 'zlam-webapp-profile-images-bucket',
            region: 'eu-central-1',
        }
    }
};

export default awsmobile;
